### ISSUE TITLE
Maximum number of accessible branches per path is two

### ISSUE THREAD

**Issue by VI-GE** [PredixDev/px-tree#4]
Hello,

In my testing if I make a path with multiple branches only two of them (the topmost two) are accessible, after that the children are shown as leafs instead of branches.

For example for the following items json:

`
    [{
        "label": "Root",
        items: [
            {
                label: "Branch 1",
                items: [
                    {
                        label: "Branch 2",
                        items: [
                            {
                                label: "Branch 3",
                                items: [
                                    {
                                        label: "Branch 4",
                                        items: [
                                            {
                                                label: "Branch 5"
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }
    ];
`

Branch 2 is shown as a leaf and can't be expanded

I have not seen this be documented anywhere, is this normal?

Thank you

**Comment by randyaskin** [comment]
Seems to be a major issue in my recursion logic. Taking a look.

**Comment by randyaskin** [comment]
Fixed in v2.0.2, thanks for pointing it out.
